### ISSUE TITLE
Force Print // Not open OS Popup

### ISSUE THREAD

**Issue by Aylay** [mycurelabs/vue-html-to-paper#74]
Hi,

Is there any solution to force the printer without open a new tap and the OS popup ?

My goal is : 
- Click on a button
- Print directly

Thank you

**Comment by jofftiquez** [comment]
Hello, I believe this would not be possible because the idea of this plugin is "print by context" or just a part of the page. The whole functionality of the printing process relies on the opened window/pop-up/page itself. Whatever is on the page, it will print. That's why I created this to:

1. get the portion of the page you want to print
2. put that potion on a new window
3. print whatever is shown in the window

This way you will have more control over what to print or not. 

Thank you for your idea.
